---
title: "Bootstrapping"
author: "Xue Zhang"
date: "2023-11-16"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

# Generate a relevant example



```{r}
n_samp = 250

sim_df_const = 
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error)

sim_df_nonconst = sim_df_const |>
  mutate(
    error = error * .75 * x,
    y = 2 + 3 * x + error
  )
```


```{r}
sim_df =
  bind_rows(const = sim_df_const, nonconst = sim_df_nonconst, .id = "data_source")

sim_df |>
  ggplot(aes(x = x, y = y)) +
  geom_point(alpha = .5) +
  stat_smooth(method = "lm") +
  facet_grid(~data_source)
```

```{r}
lm(y ~x, data = sim_df_const) |>
  broom::tidy() |>
  knitr::kable(digits = 3)
```

```{r}
lm(y ~ x, data = sim_df_nonconst) |>
  broom::tidy() |>
  knitr::kable(digits = 3)
```



# Drawing one bootstrap sample

```{r}
boot_sample = function(df) {
  sample_frac(df, replace = TRUE)
}
```


```{r}
boot_sample(sim_df_nonconst) |>
  ggplot(aes(x = x, y = y)) +
  geom_point(alpha = .5) +
  stat_smooth(method = "lm")
```

# Drawing many bootstrap samples


```{r}
boot_straps =
  tibble(strap_number = 1:1000) |>
  mutate(
    strap_sample = map(strap_number, \(i) boot_sample(df = sim_df_nonconst))
  )

boot_straps
```


```{r}
boot_straps |>
  slice(1:3) |>
  mutate(strap_sample = map(strap_sample, arrange, x)) |>
  pull(strap_sample)
```


```{r}
boot_straps |>
  slice(1:3) |>
  unnest(strap_sample) |>
  ggplot(aes(x = x, y = y)) +
  geom_point(alpha = .5) +
  stat_smooth(method = "lm", se = FALSE) +
  facet_grid(~strap_number)
```



# Analyzing bootstrap samples



```{r}
bootstrap_results =
  boot_straps |>
  mutate(
    models = map(strap_sample, \(df) lm(y ~ x, data = df)),
    results = map(models, broom::tidy)) |>
  select(-strap_sample, -models) |>
  unnest(results)
```

try to summarize these results -- get a bootstrap SE

```{r}
bootstrap_results |>
  group_by(term) |>
  summarize(boot_se = sd(estimate)) |>
  knitr::kable(digits = 3)
```


```{r}
bootstrap_results |>
  group_by(term) |>
  summarize(
    ci_lower = quantile(estimate, 0.025),
    ci_upper = quantile(estimate, 0.975))
```


```{r}
boot_straps |>
  unnest(strap_sample) |>
  ggplot(aes(x = x, y = y)) +
  geom_line(aes(group = strap_number), stat = "smooth", method = "lm", se = FALSE, alpha = .1, color = "blue") +
  geom_point(data = sim_df_nonconst, alpha = .5)
```


`bootstrap`

```{r}
boot_straps =
  sim_df_nonconst |>
  modelr::bootstrap(n = 1000)

boot_straps |>
  pull(strap) |>
  nth(1)
```


```{r}
boot_straps |>
  pull(strap) |>
  nth(1) |>
  as_tibble()
```


```{r}
sim_df_nonconst |>
  modelr::bootstrap(n = 1000) |>
  mutate(
    models = map(strap, \(df) lm(y ~ x, data = df)),
    results = map(models, broom::tidy)) |>
  select(-strap, -models) |>
  unnest(results) |>
  group_by(term) |>
  summarize(boot_se = sd(estimate))
```


```{r}
sim_df_const |>
  modelr::bootstrap(n = 1000) |>
  mutate(
    models = map(strap, \(df) lm(y ~ x, data = df)),
    results = map(models, broom::tidy)) |>
  select(-strap, -models) |>
  unnest(results) |>
  group_by(term) |>
  summarize(boot_se = (estimate))
```

# Airbnb data


```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |>
  mutate(stars = review_scores_location / 2) |>
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |>
  filter(borough != "Staten Island") |>
  drop_na(price, stars) |>
  select(price, stars, borough, neighborhood, room_type)
```

Let's fit a regression of `price` on other variables and look at residuals

```{r}
nyc_airbnb |>
  ggplot(aes(x = stars, y = price, color = room_type)) +
  geom_point()
```

```{r}
nyc_airbnb |>
  filter(borough == "Manhattan") |>
  modelr::bootstrap(n = 1000) |>
  mutate(
    models = map(strap, \(df) lm(price ~ stars + room_type, data = df)),
    results = map(models, broom::tidy) ) |>
  select(results) |>
  unnest(results) |>
  filter(term == "stars") |>
  ggplot(aes(x = estimate)) + geom_density()
```