---
title: "linear_models"
author: "Xue Zhang"
date: "2023-11-09"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```


Model fitting

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |>
  mutate(stars = review_scores_location / 2) |>
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |>
  filter(borough != "Staten island") |>
  select(price, stars, borough, neighborhood, room_type)
```

Let's fit a model!

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

Let's look at the `fit`

```{r}
nyc_airbnb = 
  nyc_airbnb |>
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type))

fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

```{r}
summary(fit)
summary(fit)$coef
coef(fit)
fitted.values(fit)
```

tidy up the output instead

```{r}
fit |>
  broom::glance()
```

```{r}
fit |>
  broom::tidy()
```

```{r}
fit |>
  broom::tidy() |>
  select(term, estimate, p.value) |>
  mutate(term = str_replace(term, "^borough", "Borough: ")) |>
  knitr::kable(digits = 3)
```



